spring:
  application:
    name: api-gateway
    
server:
  port: 8079
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8032/eureka/
  instance:
    hostname: localhost
    
    
zuul:
  routes:
    advisory-persistence:
      path: /advisory-persistence/**
      url: http://localhost:11001
    advisory:
      path: /advisory/**
      url: http://localhost:11002
    policy-db-service:
      path: /policy-db-service/**
      url: http://localhost:11003
    policy-service:
      path: /policy-service/**
      url: http://localhost:11004
    rule-engine:
      path: /rule-engine/**
      url: http://localhost:11005
    user-db-service:
      path: /user-db-service/**
      url: http://localhost:11006